[package]
name = "transadif"
version = "0.1.0"
edition = "2021"
authors = ["TransADIF Contributors"]
description = "A command-line tool for processing and transcoding ADIF files"
license = "MIT"

[[bin]]
name = "transadif"
path = "src/main.rs"

[[bin]]
name = "test_runner"
path = "src/bin/test_runner.rs"

[lib]
name = "transadif"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
encoding_rs = "0.8"
regex = "1.10"
thiserror = "1.0"
anyhow = "1.0"
unicode-normalization = "0.1"
unidecode = "0.3"

[dev-dependencies]
tempfile = "3.8"
