[package]
name = "transadif"
version = "0.1.0"
edition = "2021"
description = "A command-line tool for dealing with text encoding issues in ADIF files"
authors = ["Sebastian Delmont KI2D <ki2d@ham2k.net> - Ham2K Technologies"]
license = "MIT"

[[bin]]
name = "transadif"
path = "src/main.rs"

[[bin]]
name = "test_runner"
path = "src/bin/test_runner.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
encoding_rs = "0.8"
regex = "1.10"
thiserror = "1.0"
anyhow = "1.0"
unicode-normalization = "0.1"
unidecode = "0.3"

[dev-dependencies]
tempfile = "3.8"
